import json

# Complete service catalog from user's data
services = [
    # Almacenamiento
    {"nombre": "Mapeo de carpetas compartidas", "tipo": "Requerimiento", "categoria": "Almacenamiento", "dependencias": "Server File", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "4 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Cambios de usuario en carpeta compartida", "tipo": "Requerimiento", "categoria": "Almacenamiento", "dependencias": "Server File", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Media", "sla": "8 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "La carpeta no esta disponible", "tipo": "Incidente", "categoria": "Almacenamiento", "dependencias": "Server File", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Baja", "sla": "20 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Alta de usuario a carpeta compartida", "tipo": "Requerimiento", "categoria": "Almacenamiento", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Baja de usuario en carpeta compartida", "tipo": "Requerimiento", "categoria": "Almacenamiento", "dependencias": "Server File", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Permisos de acceso a servidor", "tipo": "Requerimiento", "categoria": "Almacenamiento", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "3", "prioridad": "Media", "sla": "12 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    
    # Aplicaciones internas
    {"nombre": "Requerimientos varios (aplicaciones)", "tipo": "Requerimiento", "categoria": "Aplicaciones internas", "dependencias": "Servidores de desarrollo", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "24 horas", "cliente": "Desarrollo Y BD", "gruposDeAtencion": "Desarrollo Y BD"},
    
    # Computo Personal
    {"nombre": "Robo de equipo cómputo", "tipo": "Incidente", "categoria": "Computo Personal", "dependencias": "Acta de Robo", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "32 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Hojas de liberación", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "CMDB", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Prestamo de equipo/cargador", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Solicitud de proyector y Poly", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    {"nombre": "Solicitud de Reporte", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "20 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Autorización, adquisición y asignación periféricos", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Vo. Bo. Lider de área, ordenes de compra, Sharepoint", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Baja", "sla": "180 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    {"nombre": "Instalación de periféricos", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Media", "sla": "12 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Respaldo de informacion de equipo", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Vo. Bo. Lider de área, Rutas con accesos y permisos, Sharepoint", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Baja", "sla": "20 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Autorización, adquisición y asignación de Monitor, Teclado o Mouse", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Vo. Bo. Lider de área, Equipo en existencia o proveedor de cómputo", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Baja", "sla": "180 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    {"nombre": "Soporte a periféricos (Pantalla, CPU, Mouse, Teclado, Pila, Cargador, Memoria, Disco Duro, proyector)", "tipo": "Incidente", "categoria": "Computo Personal", "dependencias": "Proveedor del equipo (de ser necesario)", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "20 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Bajo rendimiento equipo computo", "tipo": "Incidente", "categoria": "Computo Personal", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Baja", "sla": "20 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Falla en equipo de computo", "tipo": "Incidente", "categoria": "Computo Personal", "dependencias": "Garantías de proveedor del equipo (de ser necesario)", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "40 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Migracion de informacion", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Vo. Bo. Lider de área, Rutas con accesos y permisos, Sharepoint", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "20 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    {"nombre": "ABC de herramientas usuario", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Solicitud de RH y base de datos activa", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "32 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    {"nombre": "Asignacion de equipo nuevo usuario", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Solicitud de RH y base de datos activa", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "3", "prioridad": "Media", "sla": "20 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Baja de equipo computo", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Solicitud de RH y base de datos activa", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Reimpresion de Responsiva", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "3", "prioridad": "Media", "sla": "12 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Permisos de administrador", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Vo. Bo Lider", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Cambio de equipo computo", "tipo": "Requerimiento", "categoria": "Computo Personal", "dependencias": "Vo. Bo del lider por mejorar rendimiento laboral", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "40 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    
    # Correo Electrónico
    {"nombre": "No Sincroniza One Drive", "tipo": "Incidente", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Redireccionamiento de correo", "tipo": "Requerimiento", "categoria": "Correo electrónico", "dependencias": "TENANT 365, autorización propietario de la cuenta", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Cambio de contraseña correo", "tipo": "Requerimiento", "categoria": "Correo electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "2 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Respaldo de correo electronico", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "12 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Configuracion de Outlook", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Resteo de Autenticador", "tipo": "Requerimiento", "categoria": "Correo electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "2hrs", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Creacion de buzon compartido", "tipo": "Requerimiento", "categoria": "Correo electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Media", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Alta baja o cambios de Buzon Compartido", "tipo": "Requerimiento", "categoria": "Correo electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Degradación de correo M365", "tipo": "Incidente", "categoria": "Correo electrónico", "dependencias": "TENANT 365, Partner", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "40 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Solicitud de Reportes M365", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Alta de correo M365", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Baja de correo M365", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Correo fuera de Servicio M 365", "tipo": "Incidente", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "1", "prioridad": "Alta", "sla": "4 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Fallo en envío y recepción de correo", "tipo": "Incidente", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "4 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Creación de lista de distribución", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Media", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Baja de lista de distribución", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Cambio a lista de distribución", "tipo": "Requerimiento", "categoria": "Correo Electrónico", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    
    # Directorio Activo
    {"nombre": "Desbloqueo de cuenta", "tipo": "Requerimiento", "categoria": "Directorio Activo", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "2 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Cambio de contraseña a usuario", "tipo": "Requerimiento", "categoria": "Directorio Activo", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "2 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Cambio de fondo de pantalla", "tipo": "Requerimiento", "categoria": "Directorio Activo", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "4 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Falla en el servicio", "tipo": "Incidente", "categoria": "Directorio Activo", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Modificación de datos", "tipo": "Requerimiento", "categoria": "Directorio Activo", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Alta de usuario, equipo", "tipo": "Requerimiento", "categoria": "Directorio Activo", "dependencias": "Directorio Activo", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    
    # ERP
    {"nombre": "Soporte Funcional", "tipo": "Incidente", "categoria": "ERP", "dependencias": "SAP CONCUR, Solicitud completa y servidores de desarrollo disponibles", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "20 horas", "cliente": "ERP", "gruposDeAtencion": "ERP"},
    {"nombre": "Mantenimiento de Usuarios SAP BO", "tipo": "Requerimiento", "categoria": "ERP", "dependencias": "SAP BO, Solicitud completa y servidores de desarrollo disponibles", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "16 horas", "cliente": "aplicativos", "gruposDeAtencion": "aplicativos"},
    {"nombre": "Generación de consultas de explotación de la información", "tipo": "Requerimiento", "categoria": "ERP", "dependencias": "SAP BO, Solicitud completa y servidores de desarrollo disponibles", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Baja", "sla": "40 horas", "cliente": "ERP", "gruposDeAtencion": "ERP"},
    {"nombre": "Mantenimiento de Usuarios SAP CONCUR", "tipo": "Requerimiento", "categoria": "ERP", "dependencias": "SAP CONCUR, Solicitud completa y servidores de desarrollo disponibles", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "aplicativos", "gruposDeAtencion": "aplicativos"},
    
    # Impresión
    {"nombre": "Configuración de carpeta para escaneo local", "tipo": "Requerimiento", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "2 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Sustitución de Toner Foraneas", "tipo": "Requerimiento", "categoria": "Impresión", "dependencias": "Inplant Impresoras, proveedor", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "24 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Sustitución de Toner corporativo", "tipo": "Requerimiento", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "2 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Problemas configuiración del keyscan para impresión y copiado", "tipo": "Incidente", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "4 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Mantenimiento impresoras", "tipo": "Requerimiento", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Configuración de impresora", "tipo": "Requerimiento", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Configuiración del keyscan para impresión y copiado", "tipo": "Requerimiento", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Falla de impresora (general)", "tipo": "Incidente", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Falla de impresión (usuario)", "tipo": "Incidente", "categoria": "Impresión", "dependencias": "Inplant Impresoras", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    
    # Infraestructura
    {"nombre": "Alta, baja o cambio de servidor/switch", "tipo": "Requerimiento", "categoria": "Infraestructura", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "12 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Mantenimiento a servidores", "tipo": "Requerimiento", "categoria": "Infraestructura", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "24 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    {"nombre": "Mantenimiento a switches", "tipo": "Requerimiento", "categoria": "Infraestructura", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Servidores/Respaldos/Storage", "gruposDeAtencion": "Servidores/Respaldos/Storage"},
    
    # Redes
    {"nombre": "Configuración de VPN", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "Firewall", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Alta", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Alta de usuario de VPN", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "Firewall, Vo Bo Lider", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Alta", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Reseteo password usuario VPN", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "Firewall", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "2 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Acceso a la red de invitados", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "Firewall", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Configurar equipo acceso a internet", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Falla en equipo de telecomunicaciones", "tipo": "Incidente", "categoria": "Redes", "dependencias": "Respaldo de equipo, equipo backup", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "1", "prioridad": "critica", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Solicitud de cable de red", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Solicitud de Reporte Redes", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "Firewall", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Baja de usuario de VPN", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "Firewall, solicitud de RH", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Alta", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Alta, baja o cambio de enlaces de internet", "tipo": "Requerimiento", "categoria": "Redes", "dependencias": "CARRIER, Firewall, Vo Bo Lider", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Caída de enlace Foráneos", "tipo": "Incidente", "categoria": "Redes", "dependencias": "CARRIER", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Baja", "sla": "20 Horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Caída de enlace Local", "tipo": "Incidente", "categoria": "Redes", "dependencias": "CARRIER", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Sin señal wifi", "tipo": "Incidente", "categoria": "Redes", "dependencias": "Firewall", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Sin salida a Internet", "tipo": "Incidente", "categoria": "Redes", "dependencias": "CARRIER, Firewall", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    
    # Requerimientos Especiales
    {"nombre": "Apoyo a UN´s en procesos de licitación", "tipo": "Requerimiento", "categoria": "Requerimientos Especiales", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "6 horas", "cliente": "EXTRAORDINARIOS", "gruposDeAtencion": "EXTRAORDINARIOS"},
    {"nombre": "Apoyo a Presidencia y Direcciones", "tipo": "Requerimiento", "categoria": "Requerimientos Especiales", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "6 horas", "cliente": "EXTRAORDINARIOS", "gruposDeAtencion": "EXTRAORDINARIOS"},
    {"nombre": "Apoyo circuito cerrado CCTV", "tipo": "Requerimiento", "categoria": "Requerimientos Especiales", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    
    # Seguridad
    {"nombre": "Falla en equipo de seguridad", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "Respaldo de equipo, equipo backup", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "1", "prioridad": "critica", "sla": "8 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Generación de reporte", "tipo": "Requerimiento", "categoria": "Seguridad", "dependencias": "Firewall, DLP, consola Antivirus", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "12 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Acceso/bloqueo de dominios Anti-spam", "tipo": "Requerimiento", "categoria": "Seguridad", "dependencias": "Hornet", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Perdida / Extravío de info / DP", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Uso/ acceso/ tratamiento no autorizado de info / DP", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Daño / Alteración /modificación no autorizado de info / DP", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Robo de Info / DP", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "DLP", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Indisponibilidad / Denegacion de Servicios (DDoS)", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "Firewall", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Virus", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "Cytomic", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    {"nombre": "Spam / Malware", "tipo": "Incidente", "categoria": "Seguridad", "dependencias": "Cytomic", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Seguridad", "gruposDeAtencion": "Seguridad"},
    
    # Sharepoint M365
    {"nombre": "Solicitud de acceso a sitios Sharepoint", "tipo": "Requerimiento", "categoria": "Sharepoint M365", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "4 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Alta de sitios compatidos", "tipo": "Requerimiento", "categoria": "Sharepoint M365", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Baja de sitios comaprtidos", "tipo": "Requerimiento", "categoria": "Sharepoint M365", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Cambios en sitios compartidos", "tipo": "Requerimiento", "categoria": "Sharepoint M365", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Respaldo de sitios compartidos", "tipo": "Requerimiento", "categoria": "Sharepoint M365", "dependencias": "TENANT 365", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "24 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    {"nombre": "Degradación de acceso a sitios", "tipo": "Incidente", "categoria": "Sharepoint M365", "dependencias": "TENANT 365, Partner", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "24 horas", "cliente": "MS 365", "gruposDeAtencion": "MS 365"},
    
    # Software
    {"nombre": "Falla de software", "tipo": "Incidente", "categoria": "Software", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Configuracion del Sistema Operativo", "tipo": "Requerimiento", "categoria": "Software", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Configuracion de software", "tipo": "Requerimiento", "categoria": "Software", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "20 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Autorizacion y Adquisición de Software Ofimatica", "tipo": "Requerimiento", "categoria": "Software", "dependencias": "Vo. Bo Lider", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Baja", "sla": "40 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    {"nombre": "Autorizacion y Adquisición de Software NO Ofimatica", "tipo": "Requerimiento", "categoria": "Software", "dependencias": "vo. Bo Líder", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "3", "prioridad": "Baja", "sla": "40 horas", "cliente": "Soporte Ti", "gruposDeAtencion": "Soporte Ti"},
    {"nombre": "Activación de licencia OFFICE", "tipo": "Requerimiento", "categoria": "Software", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    {"nombre": "Instalacion de Software", "tipo": "Requerimiento", "categoria": "Software", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Mesa de Servicio", "gruposDeAtencion": "Mesa de Servicio"},
    
    # Telefonía Fija
    {"nombre": "Sin servicio de telefonia (usuario)", "tipo": "Incidente", "categoria": "Telefonía Fija", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "4 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Sin servicio de telefonia (general)", "tipo": "Incidente", "categoria": "Telefonía Fija", "dependencias": "Call Manager", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "20 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Solicitud de Reporte Telefonía", "tipo": "Requerimiento", "categoria": "Telefonía Fija", "dependencias": "Call Manager", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Alta de extension", "tipo": "Requerimiento", "categoria": "Telefonía Fija", "dependencias": "Solicitud de RH y base de datos activa", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Baja de extension", "tipo": "Requerimiento", "categoria": "Telefonía Fija", "dependencias": "Solicitud de RH y base de datos activa", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Modificacion de extension", "tipo": "Requerimiento", "categoria": "Telefonía Fija", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "2", "prioridad": "Media", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Alta de clave telefonica", "tipo": "Requerimiento", "categoria": "Telefonía Fija", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "2", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Baja de clave telefonica", "tipo": "Requerimiento", "categoria": "Telefonía Fija", "dependencias": "Solicitud de RH y base de datos activa", "cicloDeVida": "Activos", "impacto": "3", "urgencia": "1", "prioridad": "Alta", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"},
    {"nombre": "Modificación a clave telefonica", "tipo": "Requerimiento", "categoria": "Telefonía Fija", "dependencias": "NA", "cicloDeVida": "Activos", "impacto": "1", "urgencia": "2", "prioridad": "Alta", "sla": "8 horas", "cliente": "Telecomunicaciones", "gruposDeAtencion": "Telecomunicaciones"}
]

# Write to JSON file
with open('src/Config/catalogo.json', 'w', encoding='utf-8') as f:
    json.dump(services, f, ensure_ascii=False, indent=2)

print(f"Generated catalog with {len(services)} services")
